TrainAttack:
    linf:
        epsilon: 0.0155
        step_size: 0.01
        steps: 4
        clip_min: 0.
        clip_max: 1.
        
    l2:
        epsilon: 3.0
        step_size: 1.5
        steps: 4
        clip_min: 0.
        clip_max: 1.
    
    tr:
        max_translation: 50
        max_rotation: 30
        num_translations: 0
        num_rotations: 0
        grid_search: False
        random_steps: 10
        clip_min: 0.
        clip_max: 1.
        
    snow:
        nb_its: 4
        eps_max: 1.0
        step_size: 0.016
        resol: 224
        rand_init: True
        scale_each: False
        budget: 0.15
    
    gabor:
        nb_its: 4
        eps_max: 160
        step_size: 0.016
        resol: 224
        rand_init: True
        scale_each: False
        
    jpeg:
        nb_its: 4
        eps_max: 64.0
        step_size: 32.0
        resol: 224
        rand_init: True
        scale_each: False
        opt: "l2"
        
EvalAttack:
    linf:
        epsilon: 0.0155
        step_size: 0.004
        steps: 20
        clip_min: 0.
        clip_max: 1.
        
    l2:
        epsilon: 3.0
        step_size: 0.4
        steps: 20
        clip_min: 0.
        clip_max: 1.
    
    tr:
        max_translation: 50
        max_rotation: 30
        num_translations: 5
        num_rotations: 5
        grid_search: True
        random_steps: 0
        clip_min: 0.
        clip_max: 1. 
        
    snow:
        nb_its: 10
        eps_max: 1.0
        step_size: 0.01
        resol: 224
        rand_init: True
        scale_each: False
        budget: 0.15
        
    gabor:
        nb_its: 10
        eps_max: 160
        step_size: 0.01
        resol: 224
        rand_init: True
        scale_each: False
    
    jpeg:
        nb_its: 10
        eps_max: 64.0
        step_size: 20
        resol: 224
        rand_init: True
        scale_each: False
        opt: "l2"